Refactor to remove extra class, and use CSS vars
InputUsername/zola-hook pull request #11
Opened 2024-01-04 22:54 UTC by peterkos

## Background

Hello!

I tried using the theme, but the way dark/light mode was implemented made it hard to customize variables.

For instance, to change background color, I had to specify dark/light classes on `body` to apply a style:
```scss
body.dark-mode {
    a, a:link, a:visited {
	color: orange;
    }
}
```

Now, the following will work!
```scss
a, a:link, a:visited {
    color: orange;
}
```

Variables can now be overridden too:
```scss
:root.dark {
    --accent-color: orange;
}
```

## Contents
- Now uses CSS `var(--...)` vs. SASS variables to override them
- One set of variables, customized via `:root.dark`
  - (no longer duplicated all style code)
- Customize styles no longer nested in `body.dark` or `body.light`

2024-01-04 22:57 UTC, peterkos commented on sass/_theme.scss
> +        background-color: color-mix(in hsl, var(--tertiary) 10%, white);
Rough approximation (old vs. new)
```scss
background-color: lighten($tertiary, 10%);
background-color: color-mix(in hsl, var(--tertiary) 10%, white);
```

[Relative color syntax](https://www.matuzo.at/blog/2023/100daysof-day92/) isn't supported on FFox yet :( so this feels like an okay workaround.

2024-01-05 02:12 UTC, peterkos commented
Reviewing in split veiw vs. unified may be easier here, git diff went crazy 😆

2024-01-28 20:21 UTC, InputUsername requested changes
Thanks! Yeah, I didn't really like how the themes were implemented so this is very helpful.

>Removed `@media (prefers-dark...)`, since JS logic already handles this

I actually would prefer not to handle this in JS in case people have disabled it. Could you undo that change or at least make sure it also respects the user's dark mode setting without JS enabled?

2024-08-17 16:08 UTC, InputUsername commented
Finally had some more time to look at this (better late than never right :sweat_smile:) - made it work without JS and fixed some inconsistencies (link hover, table styles). Thanks @peterkos!

2024-08-17 16:08 UTC, merged